version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: educblue-backend-${NODE_ENV:-dev}
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-5000}
      - MONGO_URI=${MONGO_URI:-mongodb://mongo:27017/educblue_dev}
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - educblue-network
    restart: unless-stopped
networks:
  educblue-network:
    driver: bridge

  mongo:
    image: mongo:6.0
    container_name: educblue-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=educblue
    networks:
      - educblue-network

  # Redis for session storage and caching (optional)
  redis:
    image: redis:7-alpine
    container_name: educblue-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - educblue-network
