version: '3.8'

services:
  # Development services
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: educblue-backend-dev
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/educblue_dev
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - educblue-network
    profiles:
      - dev

  # Production services
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: educblue-backend-prod
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - educblue-network
    restart: unless-stopped
    profiles:
      - prod

  mongo:
    image: mongo:6.0
    container_name: educblue-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=educblue
    networks:
      - educblue-network

  # Redis for session storage and caching (optional)
  redis:
    image: redis:7-alpine
    container_name: educblue-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - educblue-network

volumes:
  mongo-data:
  redis-data:

networks:
  educblue-network:
    driver: bridge
