services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV:-development}
    container_name: ${COMPOSE_PROJECT_NAME:-educblue}-app
    ports:
      - '${PORT:-5000}:${PORT:-5000}'
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-5000}
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - educblue-network
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    container_name: ${COMPOSE_PROJECT_NAME:-educblue}-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=educblue
    networks:
      - educblue-network

  # Redis for session storage and caching (optional)
  redis:
    image: redis:7-alpine
    container_name: ${COMPOSE_PROJECT_NAME:-educblue}-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - educblue-network

volumes:
  mongo-data:
  redis-data:

networks:
  educblue-network:
    driver: bridge
